name: Build Project

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check if build artifacts were created
        run: |
          if [ -f "css/style.css" ]; then
            echo "✅ Build successful - CSS file created"
            ls -la css/
          else
            echo "❌ Build failed - CSS file not found"
            exit 1
          fi
